name: 'Test Cookbook API'
description: 'GitHub Action to test the Cookbook Api project'

inputs:
  output-directory:
    description: 'The directory where the build output will be stored'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore build output
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-build-${{ github.sha }}
        path: ${{ github.workspace }}/${{ inputs.output-directory }}
        fail-on-cache-hit: true
        restore-keys: |
          ${{ runner.os }}-build-${{ github.sha }}
          ${{ runner.os }}-build-

    - name: Test
      shell: bash
      run: |
        dotnet test '${{ inputs.output-directory }}/Cookbook.Tests.dll' --no-build --configuration Release --logger 'trx;logfilename=TestResults.trx' --results-directory '${{ github.workspace }}/TestResults'

    - name: Create test results
      if: always()
      shell: bash
      run: |
        dotnet new tool-manifest
        dotnet tool install DotnetCtrfJsonReporter --local
        dotnet tool run DotnetCtrfJsonReporter -p 'TestResults/TestResults.trx' -t 'xUnit'
        npx github-actions-ctrf ctrf/ctrf-report.json